### ISSUE TITLE
CONFIGURE: eom cargo install failed on a newly created DLVM

### ISSUE THREAD

**Issue by simonzhaoms** [gjwgit/animate#4]
```console
$ ml configure animate 
Configuring using '/home/simon/.mlhub/animate/configure.R'...

Please ask your sys admin to install the following system dependencies:
  eom cargo 

An error was encountered:

Error: Configuration can not continue at this time.
Execution halted
```

**Comment by gjwgit** [comment]
The actual error message was specifically added to the code. This configuration issue will become a mute point when we move to configuration being driven from the YAML file.

**Comment by gjwgit** [comment]
Restore assumption of root user. Works on sysadmin account on Ubuntu. 600820fece4f5e87c0f0d649814d2183c36ec1d7
