### ISSUE TITLE
README: No readme.txt when install from GitHub directly

### ISSUE THREAD

**Issue by simonzhaoms** [gjwgit/animate#5]
Need to run Makefile.

```console
$ ml readme animate 
mlhub: The 'animate' model does not have a 'README.txt' file:
  /home/simon/.mlhub/animate/README.txt


To remove installed model(s):

  $ ml remove <model>

To locally install a model downloaded from an ML Hub repository:

  $ ml install <model>


```

**Comment by gjwgit** [comment]
Maybe mlhubv3 will need to download README.md and then process it on install with

`$ pandoc -t plain README.md | awk '/^Usage$$/{exit}{print}' | perl -00pe0 > README.txt`

or something more general that extracts just the first section of the README.

**Comment by gjwgit** [comment]
Fixed in mlhubv3

**Comment by gjwgit** [comment]
Fixed in mlhubv3
